# The UI suite installs BinaryRulesLoad before requiring production files.
# All imported suites consequently exercise binary sources/the supplied package,
# including the real ELTEN dictionary and its no-argument shuffle overrides.
require_relative 'axel_pong_ui_test'
require_relative 'axel_pong_engine_test'
require_relative 'realtime_protocol_test'
require_relative 'realtime_channel_test'
require_relative 'axel_pong_audio_test'
require_relative 'axel_pong_integration_test'
require_relative 'axel_pong_rally_sync_test'
require_relative 'axel_pong_serve_input_test'
require_relative 'axel_pong_audio_feedback_test'
require_relative 'axel_pong_point_audio_test'
require_relative 'realtime_event_channel_test'
require_relative 'axel_pong_reference_test'
require_relative 'axel_pong_audio_reference_test'
require_relative 'axel_pong_hurry_test'
require_relative 'axel_pong_peer_events_test'
require_relative 'axel_pong_frame_timing_test'
require_relative 'axel_pong_mouse_client_test'
require_relative 'axel_pong_deep_parity_test'
require_relative 'axel_pong_parity_fixes_test'
require_relative 'axel_pong_source_physics_test'
require_relative 'axel_pong_source_audio_test'
require_relative 'axel_pong_source_client_test'
require_relative 'axel_pong_settings_test'
require_relative 'realtime_recovery_test'
require_relative 'realtime_delivery_test'
require_relative 'realtime_two_clients_test'
require_relative 'axel_pong_connection_recovery_test'
require_relative 'axel_pong_network_wait_test'
require_relative 'axel_pong_goal_latency_test'
puts 'PASS binary Pong: engine, protocol, channel, audio, clients, durable points and PL/EN UI'
