# encoding: UTF-8
# Regional board observations: QC client 2026.8.15, 2026-09-11.
# See docs/MONOPOLY_REGIONAL_BOARDS.md for verified data versus adaptations.
module GameRoomContent
  module MonopolyRegionalData
    # price, mortgage, six rents, in base currency units; 34 observed deeds.
    DEEDS = [
      [60,30,[2,10,30,90,160,250]],
      [60,30,[4,20,60,150,300,450]],
      [100,50,[6,30,90,270,400,550]],
      [100,50,[6,30,90,270,400,550]],
      [120,60,[8,40,100,300,450,600]],
      [140,70,[10,50,150,450,625,750]],
      [140,70,[10,50,150,450,625,750]],
      [160,80,[12,60,180,500,700,900]],
      [180,90,[14,70,200,550,750,950]],
      [180,90,[14,70,200,550,750,950]],
      [200,100,[16,80,220,600,800,1000]],
      [220,110,[18,90,250,700,875,1050]],
      [220,110,[18,90,250,700,875,1050]],
      [240,120,[20,100,300,750,925,1100]],
      [260,130,[22,110,330,800,975,1150]],
      [260,130,[22,110,330,800,975,1150]],
      [280,140,[24,120,360,850,1025,1200]],
      [300,150,[26,130,390,900,1100,1275]],
      [300,150,[26,130,390,900,1100,1275]],
      [320,160,[28,150,450,1000,1200,1400]],
      [350,175,[35,175,500,1100,1300,1500]],
      [400,200,[50,200,600,1400,1700,2000]],
      [450,225,[50,250,750,1600,1900,2200]],
      [450,225,[50,250,750,1600,1900,2200]],
      [500,250,[55,275,825,1800,2100,2400]],
      [550,275,[60,300,900,1800,2100,2400]],
      [550,275,[60,300,900,1800,2100,2400]],
      [600,300,[65,325,975,2000,2350,2700]],
      [700,350,[70,350,1050,2250,2600,3000]],
      [700,350,[70,350,1050,2250,2600,3000]],
      [750,375,[75,375,1125,2300,2650,3000]],
      [800,400,[80,400,1200,2500,3000,3500]],
      [800,400,[80,400,1200,2500,3000,3500]],
      [900,450,[90,450,1350,2800,3400,4000]],
    ].map { |price, mortgage, rents| [price, mortgage, rents.freeze].freeze }.freeze

    # First eight groups retain the existing building rules. Extra groups use
    # sampled QC costs (white/brown/magenta). Unobserved groups are priced
    # relative to their own property values by the board adapter.
    HOUSE_COSTS = { "pink" => 50, "azure" => 50, "purple" => 100, "orange" => 100,
      "red" => 150, "yellow" => 150, "green" => 200, "blue" => 200,
      "white" => 250, "brown" => 275, "magenta" => 400 }.freeze

    PROFILES = {
      "atlantic_city" => {
        money_factor: 1, currency_symbol: "$", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Start"],
          [:property, "Mediterranean avenue", "pink"],
          [:community, "Community chest"],
          [:property, "Baltic avenue", "pink"],
          [:tax, "Income tax"],
          [:railroad, "Reading railroad"],
          [:property, "Oriental avenue", "azure"],
          [:chance, "Chance"],
          [:property, "Vermont avenue", "azure"],
          [:property, "Connecticut avenue", "azure"],
          [:jail, "Jail, just visiting"],
          [:property, "Saint-Charles place", "purple"],
          [:utility, "Electric company"],
          [:property, "States avenue", "purple"],
          [:property, "Virginia avenue", "purple"],
          [:railroad, "Pennsylvania railroad"],
          [:property, "Saint-James place", "orange"],
          [:community, "Community chest"],
          [:property, "Tennessee avenue", "orange"],
          [:property, "New york avenue", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Kentucky avenue", "red"],
          [:chance, "Chance"],
          [:property, "Indiana avenue", "red"],
          [:property, "Illinois avenue", "red"],
          [:railroad, "B&O railroad"],
          [:property, "Atlantic avenue", "yellow"],
          [:property, "Ventnor avenue", "yellow"],
          [:utility, "Water works"],
          [:property, "Marvin garden", "yellow"],
          [:go_to_jail, "Go directly to jail !"],
          [:property, "Pacific avenue", "green"],
          [:property, "North Carolina avenue", "green"],
          [:community, "Community chest"],
          [:property, "Pennsylvania avenue", "green"],
          [:railroad, "Short line railroad"],
          [:chance, "Chance"],
          [:property, "Parc place", "blue"],
          [:tax_luxury, "Luxury tax"],
          [:property, "Boardwalk", "blue"],
        ]
      },
      "london" => {
        money_factor: 1, currency_symbol: "£", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Start"],
          [:property, "Old Kent Road", "pink"],
          [:community, "Community chest"],
          [:property, "Whitechapel Road", "pink"],
          [:tax, "Income tax"],
          [:railroad, "King's cross station"],
          [:property, "The Angel Islington", "azure"],
          [:chance, "Chance"],
          [:property, "Euston Road", "azure"],
          [:property, "Pentonville Road", "azure"],
          [:jail, "Jail, just visiting"],
          [:property, "Pall Mall", "purple"],
          [:utility, "Electric company"],
          [:property, "Whitehall", "purple"],
          [:property, "Northumberland Avenue", "purple"],
          [:railroad, "Marylebone station"],
          [:property, "Bow Street", "orange"],
          [:community, "Community chest"],
          [:property, "Marlborough Street", "orange"],
          [:property, "Vine Street", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Strand", "red"],
          [:chance, "Chance"],
          [:property, "Fleet street", "red"],
          [:property, "Trafalgar square", "red"],
          [:railroad, "Fenchurch street station"],
          [:property, "Leicester square", "yellow"],
          [:property, "Coventry street", "yellow"],
          [:utility, "Water works"],
          [:property, "Piccadilly", "yellow"],
          [:go_to_jail, "Go to jail !"],
          [:property, "Regent street", "green"],
          [:property, "Oxford street", "green"],
          [:community, "Community chest"],
          [:property, "Bond Street", "green"],
          [:railroad, "Liverpool Street station"],
          [:chance, "Chance"],
          [:property, "Park Lane", "blue"],
          [:tax_luxury, "Super tax"],
          [:property, "Mayfair", "blue"],
        ]
      },
      "roma" => {
        money_factor: 1, currency_symbol: "euro", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Via"],
          [:property, "Vicolo del moro", "pink"],
          [:community, "Probabilità"],
          [:property, "Vicolo dei cinque", "pink"],
          [:tax, "Tassa patrimoniale"],
          [:railroad, "Stazione Tiburtina"],
          [:property, "Lungotevere vaticano", "azure"],
          [:chance, "Imprevisti"],
          [:property, "Viale Angelico", "azure"],
          [:property, "Viale Trastevere", "azure"],
          [:jail, "Prigione, transito"],
          [:property, "Via del Tritone", "purple"],
          [:utility, "Società elettrica"],
          [:property, "Corso Rinascimento", "purple"],
          [:property, "Piazza Navona", "purple"],
          [:railroad, "Stazione Ostiense"],
          [:property, "Via Sistina", "orange"],
          [:community, "Probabilità"],
          [:property, "Corso Vittorio", "orange"],
          [:property, "Piazza di Spagna", "orange"],
          [:free_parking, "Posteggio gratuito"],
          [:property, "Via Condotti", "red"],
          [:chance, "Imprevisti"],
          [:property, "Via del Corso", "red"],
          [:property, "Largo Goldoni", "red"],
          [:railroad, "Stazione Termini"],
          [:property, "Viale Trinità dei monti", "yellow"],
          [:property, "Viale Marconi", "yellow"],
          [:utility, "Società acqua potabile"],
          [:property, "Piazza San Pietro", "yellow"],
          [:go_to_jail, "Prigione"],
          [:property, "Via della Conciliazione", "green"],
          [:property, "Corso D'Italia", "green"],
          [:community, "Probabilità"],
          [:property, "Largo San Carlo al corso", "green"],
          [:railroad, "Stazione Trastevere"],
          [:chance, "Imprevisti"],
          [:property, "Via Veneto", "blue"],
          [:tax_luxury, "Tassa di lusso"],
          [:property, "Parco del Pincio", "blue"],
        ]
      },
      "latin_america" => {
        money_factor: 3, currency_symbol: "¤", starting_cash: 9750,
        salary: 750, salary_observed: false, bank_houses: 48, bank_hotels: 18,
        layout: [
          [:start, "Start"],
          [:property, "Montevideo", "pink"],
          [:community, "Community chest"],
          [:property, "Asunción", "pink"],
          [:tax, "Income tax"],
          [:railroad, "Metro de São Paulo"],
          [:property, "La Abana", "azure"],
          [:chance, "Chance"],
          [:property, "Santiago de Cuba", "azure"],
          [:property, "Camagüey", "azure"],
          [:jail, "Jail, simple visit"],
          [:property, "San José", "purple"],
          [:utility, "Servicio de agua"],
          [:property, "Santo Domingo", "purple"],
          [:property, "Panamá", "purple"],
          [:railroad, "Metro Benito Juárez"],
          [:property, "Quito", "orange"],
          [:community, "Community chest"],
          [:property, "Guayaquil", "orange"],
          [:property, "Cuenca", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Caracas", "red"],
          [:chance, "Chance"],
          [:property, "Maracaibo", "red"],
          [:property, "Bolívar", "red"],
          [:railroad, "Metro San Martín"],
          [:property, "Lima", "yellow"],
          [:property, "Arequipa", "yellow"],
          [:utility, "corporación eléctrica"],
          [:property, "Trujillo", "yellow"],
          [:neutral, "Zone without cars"],
          [:property, "La Paz", "green"],
          [:property, "Sucre", "green"],
          [:community, "Community chest"],
          [:property, "Santa Cruz", "green"],
          [:railroad, "Metro Bolívar"],
          [:chance, "Chance"],
          [:property, "Santiago", "blue"],
          [:tax_luxury, "Luxury tax"],
          [:property, "Valparaíso", "blue"],
          [:neutral, "Public toilet"],
          [:property, "Bogotá", "white"],
          [:utility, "compañía de gas"],
          [:property, "Barranquilla", "white"],
          [:property, "Medellín", "white"],
          [:chance, "Chance"],
          [:property, "Buenos Aires", "brown"],
          [:property, "Córdoba", "brown"],
          [:railroad, "sucre station"],
          [:property, "Mar del Plata", "brown"],
          [:go_to_jail, "Go to jail !"],
          [:property, "Guadalajara", "gray"],
          [:property, "Monterrey", "gray"],
          [:community, "Community chest"],
          [:property, "Ciudad de México", "gray"],
          [:utility, "Telecomunicaciones"],
          [:property, "Brasilia", "magenta"],
          [:railroad, "metro central"],
          [:property, "São Paulo", "magenta"],
          [:property, "Río de Janeiro", "magenta"],
        ]
      },
      "barcelona" => {
        money_factor: 10000, currency_symbol: "€", starting_cash: 15000000,
        salary: 2000000, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Salida"],
          [:property, "Calle de Lauria", "pink"],
          [:community, "Caja de comunidad"],
          [:property, "Calle de Rosellón", "pink"],
          [:tax, "Impuesto sobre reintegros"],
          [:railroad, "Estación Ferrocarriles catalanes"],
          [:property, "Calle de Marina", "azure"],
          [:chance, "Suerte"],
          [:property, "Calle de Urgel", "azure"],
          [:property, "Calle de Consejo de ciento", "azure"],
          [:jail, "Visita a la cárcel"],
          [:property, "Calle de Muntaner", "purple"],
          [:utility, "Compañía Distribución de electricidad"],
          [:property, "Calle de Aribau", "purple"],
          [:property, "Avenida de Infanta Carlota", "purple"],
          [:railroad, "Apeadero Paseo de Gracia"],
          [:property, "Paseo de San Juan", "orange"],
          [:community, "Caja de comunidad"],
          [:property, "Calle de la Diputación", "orange"],
          [:property, "Calle de Aragón", "orange"],
          [:free_parking, "Parking gratuito"],
          [:property, "Plaza de Urquinaona", "red"],
          [:chance, "Suerte"],
          [:property, "Calle de Fontanella", "red"],
          [:property, "Ronda de San Pedro", "red"],
          [:railroad, "Estación de Francia"],
          [:property, "Las Ramblas", "yellow"],
          [:property, "Vía layetana", "yellow"],
          [:utility, "Compañía Distribución de aguas"],
          [:property, "Plaza de Cataluña", "yellow"],
          [:go_to_jail, "¡Vaya a la cárcel!"],
          [:property, "Avenida de Puerta del ángel", "green"],
          [:property, "Calle de Pelayo", "green"],
          [:community, "Caja de comunidad"],
          [:property, "Vía augusta", "green"],
          [:railroad, "Estación del norte"],
          [:chance, "Suerte"],
          [:property, "Calle de Balmes", "blue"],
          [:tax_luxury, "Tasa de lujo"],
          [:property, "Paseo de Gracia", "blue"],
        ]
      },
      "turkey" => {
        money_factor: 1, currency_symbol: "TL", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Baslangic"],
          [:property, "Ardahan", "pink"],
          [:community, "Toplu sans"],
          [:property, "Mus", "pink"],
          [:tax, "Gelir vergisi"],
          [:railroad, "Sabiha Gokcen Hava alani"],
          [:property, "Nevsehir", "azure"],
          [:chance, "Sans"],
          [:property, "Sivas", "azure"],
          [:property, "Mugla", "azure"],
          [:jail, "Hapis, sadece ziyaret."],
          [:property, "Rize", "purple"],
          [:utility, "Tedas"],
          [:property, "Artvin", "purple"],
          [:property, "Zonguldak", "purple"],
          [:railroad, "Esenboga Hava alani"],
          [:property, "Kutahya", "orange"],
          [:community, "Toplu sans"],
          [:property, "Aydin", "orange"],
          [:property, "Burdur", "orange"],
          [:free_parking, "Ucretsiz park"],
          [:property, "Diyarbakirr", "red"],
          [:chance, "Sans"],
          [:property, "Elazig", "red"],
          [:property, "Erzurum", "red"],
          [:railroad, "Adnan Menderes Hava alani"],
          [:property, "isparta", "yellow"],
          [:property, "Malatya", "yellow"],
          [:utility, "Devlet su isleri"],
          [:property, "Balikesir", "yellow"],
          [:go_to_jail, "Hapishane!"],
          [:property, "Adana", "green"],
          [:property, "Samsun", "green"],
          [:community, "Toplu sans"],
          [:property, "Antalya", "green"],
          [:railroad, "Ataturk Hava alani"],
          [:chance, "Sans"],
          [:property, "Ankara", "blue"],
          [:tax_luxury, "Ozel kullanim vergisi"],
          [:property, "istanbul", "blue"],
        ]
      },
      "slovakia" => {
        money_factor: 1, currency_symbol: "€", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Štart"],
          [:property, "Stakčín", "pink"],
          [:community, "Pokladňa"],
          [:property, "Nová Sedlica", "pink"],
          [:tax, "Daň z príjmu"],
          [:railroad, "Letisko Bidovce"],
          [:property, "Trnava", "azure"],
          [:chance, "Šanca"],
          [:property, "Piešťany", "azure"],
          [:property, "Galanta", "azure"],
          [:jail, "Väzenie, iba návšteva"],
          [:property, "Nitra", "purple"],
          [:utility, "Jadrová elektráreň Jaslovské Bohunice"],
          [:property, "Nové zámky", "purple"],
          [:property, "Komárno", "purple"],
          [:railroad, "Letisko Sliač"],
          [:property, "Banská Bystrica", "orange"],
          [:community, "Pokladňa"],
          [:property, "Zvolen", "orange"],
          [:property, "Žiar nad Hronom", "orange"],
          [:free_parking, "Bezplatné parkovanie"],
          [:property, "Liptovský Mikuláš", "red"],
          [:chance, "Šanca"],
          [:property, "Liptovský Hrádok", "red"],
          [:property, "Ružomberok", "red"],
          [:railroad, "Letisko Košice"],
          [:property, "Prešov", "yellow"],
          [:property, "Poprad", "yellow"],
          [:utility, "Jadrová elektráreň Mochovce"],
          [:property, "Spišská nová ves", "yellow"],
          [:go_to_jail, "Marš do väzenia!"],
          [:property, "Prievidza", "green"],
          [:property, "Handlová", "green"],
          [:community, "Pokladňa"],
          [:property, "Bojnice", "green"],
          [:railroad, "Letisko Bratislava"],
          [:chance, "Šanca"],
          [:property, "Košice", "blue"],
          [:tax_luxury, "Superdaň"],
          [:property, "Bratislava", "blue"],
        ]
      },
      "serbia" => {
        money_factor: 10000, currency_symbol: "RSD", starting_cash: 15000000,
        salary: 2000000, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Horgoš"],
          [:property, "Jagodina", "pink"],
          [:community, "Lutrija"],
          [:property, "Pirot", "pink"],
          [:tax, "Porez"],
          [:railroad, "Glavna železnička stanica - Beograd"],
          [:property, "Sremska Mitrovica", "azure"],
          [:chance, "Šansa"],
          [:property, "Sombor", "azure"],
          [:property, "Požarevac", "azure"],
          [:jail, "Centralni zatvor, samo poseta"],
          [:property, "Užice", "purple"],
          [:utility, "Hidro-elektrana Đerdap"],
          [:property, "Vranje", "purple"],
          [:property, "Šabac", "purple"],
          [:railroad, "Železnička stanica Novi Sad"],
          [:property, "Kruševac", "orange"],
          [:community, "Lutrija"],
          [:property, "Valjevo", "orange"],
          [:property, "Kraljevo", "orange"],
          [:free_parking, "Besplatan parking"],
          [:property, "Leskovac", "red"],
          [:chance, "Šansa"],
          [:property, "Smederevo", "red"],
          [:property, "Zrenjanin", "red"],
          [:railroad, "Aerodrom Car Konstantin - Niš"],
          [:property, "Čačak", "yellow"],
          [:property, "Novi Pazar", "yellow"],
          [:utility, "Termoelektrana Kolubara"],
          [:property, "Pančevo", "yellow"],
          [:go_to_jail, "Pravo u zatvor!"],
          [:property, "Subotica", "green"],
          [:property, "Kragujevac", "green"],
          [:community, "Lutrija"],
          [:property, "Niš", "green"],
          [:railroad, "Aerodrom Nikola Tesla - Beograd"],
          [:chance, "Šansa"],
          [:property, "Novi Sad", "blue"],
          [:tax_luxury, "Taksa"],
          [:property, "Beograd", "blue"],
        ]
      },
      "czechia" => {
        money_factor: 25, currency_symbol: "CZK", starting_cash: 37500,
        salary: 5000, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Start"],
          [:property, "Děčín", "pink"],
          [:community, "Pokladna"],
          [:property, "Písek", "pink"],
          [:tax, "Daň z příjmů"],
          [:railroad, "Plzeň hlavní nádraží"],
          [:property, "Karlovy Vary", "azure"],
          [:chance, "Šance"],
          [:property, "Luhačovice", "azure"],
          [:property, "Teplice", "azure"],
          [:jail, "Vězení, pouze návštěva"],
          [:property, "Kutná Hora", "purple"],
          [:utility, "Jaderná elektrárna Dukovany"],
          [:property, "Telč", "purple"],
          [:property, "Český Krumlov", "purple"],
          [:railroad, "Ostrava hlavní nádraží"],
          [:property, "Most", "orange"],
          [:community, "Pokladna"],
          [:property, "Jihlava", "orange"],
          [:property, "Kolín", "orange"],
          [:free_parking, "Bezplatné parkování"],
          [:property, "Zlín", "red"],
          [:chance, "Šance"],
          [:property, "Pardubice", "red"],
          [:property, "České Budějovice", "red"],
          [:railroad, "Brno hlavní nádraží"],
          [:property, "Hradec Králové", "yellow"],
          [:property, "Ústí nad Labem", "yellow"],
          [:utility, "Podolská vodárna"],
          [:property, "Olomouc", "yellow"],
          [:go_to_jail, "Marš do vězení!"],
          [:property, "Liberec", "green"],
          [:property, "Plzeň", "green"],
          [:community, "Pokladna"],
          [:property, "Ostrava", "green"],
          [:railroad, "Praha hlavní nádraží"],
          [:chance, "Šance"],
          [:property, "Brno", "blue"],
          [:tax_luxury, "Superdaň"],
          [:property, "Praha", "blue"],
        ]
      },
      "russia" => {
        money_factor: 1, currency_symbol: "RUB", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Старт"],
          [:property, "Пенза", "pink"],
          [:community, "Общественная казна"],
          [:property, "Рязань", "pink"],
          [:tax, "Налог на прибыль"],
          [:railroad, "Кольцово аэропорт"],
          [:property, "Чебоксары", "azure"],
          [:chance, "Шанс"],
          [:property, "Пермь", "azure"],
          [:property, "Екатеринбург", "azure"],
          [:jail, "Тюрьма, только посещение"],
          [:property, "Сургут", "purple"],
          [:utility, "Ростелеком"],
          [:property, "Красноярск", "purple"],
          [:property, "Новосибирск", "purple"],
          [:railroad, "Толмачево аэропорт"],
          [:property, "Архангельск", "orange"],
          [:community, "Общественная казна"],
          [:property, "Северодвинск", "orange"],
          [:property, "Обнинск", "orange"],
          [:free_parking, "Бесплатная парковка"],
          [:property, "Москва", "red"],
          [:chance, "Шанс"],
          [:property, "Санкт-Петербург", "red"],
          [:property, "Воронеж", "red"],
          [:railroad, "Шереметьево аэропорт"],
          [:property, "Ростов-На-Дону", "yellow"],
          [:property, "Псков", "yellow"],
          [:utility, "Калининская Атомная станция"],
          [:property, "Барнаул", "yellow"],
          [:go_to_jail, "Отправляйтесь в тюрьму!"],
          [:property, "Челябинск", "green"],
          [:property, "Самара", "green"],
          [:community, "Общественная казна"],
          [:property, "Сыктывкар", "green"],
          [:railroad, "Пулково аэропорт"],
          [:chance, "Шанс"],
          [:property, "Курган", "blue"],
          [:tax_luxury, "Налог"],
          [:property, "Батайск", "blue"],
        ]
      },
      "ukraine" => {
        money_factor: 1, currency_symbol: "UAH", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Старт"],
          [:property, "Мелітополь", "pink"],
          [:community, "суспільний фонд"],
          [:property, "Черкаси", "pink"],
          [:tax, "Податок на прибуток"],
          [:railroad, "Львівська залізнична станція"],
          [:property, "Запоріжжя", "azure"],
          [:chance, "Шанс"],
          [:property, "Чернігів", "azure"],
          [:property, "Івано-Франківськ", "azure"],
          [:jail, "В'язниця, тільки відвідування"],
          [:property, "Вінниця", "purple"],
          [:utility, "Укртелеком"],
          [:property, "Полтава", "purple"],
          [:property, "Дніпро", "purple"],
          [:railroad, "Івано-Франківська залізнична станція"],
          [:property, "Тернопіль", "orange"],
          [:community, "суспільний фонд"],
          [:property, "Хмельницький", "orange"],
          [:property, "Луцьк", "orange"],
          [:free_parking, "Безкоштовне паркування"],
          [:property, "Рівне", "red"],
          [:chance, "Шанс"],
          [:property, "Чернівці", "red"],
          [:property, "Ужгород", "red"],
          [:railroad, "Одеська залізнична станція"],
          [:property, "Житомир", "yellow"],
          [:property, "Суми", "yellow"],
          [:utility, "Південноукраїнська АЕС"],
          [:property, "Кропивницький", "yellow"],
          [:go_to_jail, "Вирушайте до в'язниці!"],
          [:property, "Миколаїв", "green"],
          [:property, "Херсон", "green"],
          [:community, "суспільний фонд"],
          [:property, "Одеса", "green"],
          [:railroad, "Київська залізнична станція"],
          [:chance, "Шанс"],
          [:property, "Львів", "blue"],
          [:tax_luxury, "Податок"],
          [:property, "Київ", "blue"],
        ]
      },
      "romania" => {
        money_factor: 10000, currency_symbol: "RON", starting_cash: 35000000,
        salary: 2500000, salary_observed: false, bank_houses: 48, bank_hotels: 18,
        layout: [
          [:start, "Pornire"],
          [:property, "Vaslui", "pink"],
          [:community, "Cutia Milei"],
          [:property, "Tulcea", "pink"],
          [:tax, "Impozit pe venit"],
          [:railroad, "Gara de Nord"],
          [:property, "Călărași", "azure"],
          [:chance, "Șansă"],
          [:property, "Slatina", "azure"],
          [:property, "Alexandria", "azure"],
          [:jail, "La secție, doar în trecere."],
          [:property, "Galați", "purple"],
          [:utility, "Electrica"],
          [:property, "Brăila", "purple"],
          [:property, "Buzău", "purple"],
          [:railroad, "Aeroportul Internaţional Henri Coandă"],
          [:property, "Suceava", "orange"],
          [:community, "Cutia Milei"],
          [:property, "Târgoviște", "orange"],
          [:property, "Giurgiu", "orange"],
          [:free_parking, "Parcare Gratuită"],
          [:property, "Râmnicu-Vâlcea", "red"],
          [:chance, "Șansă"],
          [:property, "Bistrița-Năsăud", "red"],
          [:property, "Focșani", "red"],
          [:railroad, "Metrorex"],
          [:property, "Ploiești", "yellow"],
          [:property, "Craiova", "yellow"],
          [:utility, "Apă-Canal"],
          [:property, "Pitești", "yellow"],
          [:neutral, "Zonă Pietonală"],
          [:property, "Botoșani", "green"],
          [:property, "Bacău", "green"],
          [:community, "Cutia Milei"],
          [:property, "Miercurea Ciuc", "green"],
          [:railroad, "Gara Constanța"],
          [:chance, "Șansă"],
          [:property, "Constanța", "blue"],
          [:tax_luxury, "Taxă de Lux"],
          [:property, "Sinaia", "blue"],
          [:go_to_jail, "Mergi la Închisoare!"],
          [:property, "Baia Mare", "white"],
          [:utility, "Rompetrol"],
          [:property, "Satu Mare", "white"],
          [:property, "Târgu Mureș", "white"],
          [:chance, "Șansă"],
          [:property, "Deva", "brown"],
          [:property, "Reșița", "brown"],
          [:railroad, "Gara Bușteni"],
          [:property, "Oradea", "brown"],
          [:neutral, "Toaletă Publică"],
          [:property, "Sibiu", "gray"],
          [:property, "Brașov", "gray"],
          [:community, "Cutia Milei"],
          [:property, "Iași", "gray"],
          [:utility, "Romtelecom"],
          [:property, "Cluj-Napoca", "magenta"],
          [:railroad, "Gara Cluj-Napoca"],
          [:property, "Timișoara", "magenta"],
          [:property, "București", "magenta"],
        ]
      },
      "balkans" => {
        money_factor: 2, currency_symbol: "¤", starting_cash: 7000,
        salary: 500, salary_observed: false, bank_houses: 48, bank_hotels: 18,
        layout: [
          [:start, "Старт"],
          [:property, "Durrës", "pink"],
          [:community, "Community chest"],
          [:property, "Tirana", "pink"],
          [:tax, "Income tax"],
          [:railroad, "Pristina Railway Station"],
          [:property, "Peja", "azure"],
          [:chance, "Chance"],
          [:property, "Prizren", "azure"],
          [:property, "Pristina", "azure"],
          [:jail, "Jail, simple visit"],
          [:property, "Budva", "purple"],
          [:utility, "Electric company"],
          [:property, "Kotor", "purple"],
          [:property, "Podgorica", "purple"],
          [:railroad, "Sarajevo Railway Station"],
          [:property, "Mostar", "orange"],
          [:community, "Community chest"],
          [:property, "Banja Luka", "orange"],
          [:property, "Sarajevo", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Ohrid", "red"],
          [:chance, "Chance"],
          [:property, "Bitola", "red"],
          [:property, "Skopje", "red"],
          [:railroad, "Ljubljana Railway Station"],
          [:property, "Koper", "yellow"],
          [:property, "Maribor", "yellow"],
          [:utility, "Water works"],
          [:property, "Ljubljana", "yellow"],
          [:neutral, "Coastline"],
          [:property, "Dubrovnik", "green"],
          [:property, "Split", "green"],
          [:community, "Community chest"],
          [:property, "Zagreb", "green"],
          [:railroad, "Sofia Central Railway Station"],
          [:chance, "Chance"],
          [:property, "Plovdiv", "blue"],
          [:tax_luxury, "Luxury tax"],
          [:property, "Sofia", "blue"],
          [:go_to_jail, "Go directly to jail!"],
          [:property, "Niš", "white"],
          [:utility, "Oil company"],
          [:property, "Novi Sad", "white"],
          [:property, "Belgrade", "white"],
          [:chance, "Chance"],
          [:property, "Timișoara", "brown"],
          [:property, "Cluj-Napoca", "brown"],
          [:railroad, "Bucharest North Railway Station"],
          [:property, "Bucharest", "brown"],
          [:neutral, "Local market"],
          [:property, "Ioannina", "gray"],
          [:property, "Patras", "gray"],
          [:community, "Community chest"],
          [:property, "Thessaloniki", "gray"],
          [:utility, "Telecom company"],
          [:property, "Bursa", "magenta"],
          [:railroad, "Sirkeci Railway Station"],
          [:property, "Edirne", "magenta"],
          [:property, "Istanbul", "magenta"],
        ]
      },
      "indonesia" => {
        money_factor: 10000, currency_symbol: "Rupiah", starting_cash: 35000000,
        salary: 2500000, salary_observed: false, bank_houses: 48, bank_hotels: 18,
        layout: [
          [:start, "Mulai"],
          [:property, "Manokwari", "pink"],
          [:community, "Kotak Amal"],
          [:property, "Kupang", "pink"],
          [:tax, "Pajak Penghasilan"],
          [:railroad, "Stasiun Hall Bandung"],
          [:property, "Cianjur", "azure"],
          [:chance, "Kesempatan"],
          [:property, "Palu", "azure"],
          [:property, "Karawang", "azure"],
          [:neutral, "Toilet Umum"],
          [:property, "Serang", "purple"],
          [:utility, "Perusahaan Daerah Air Minum (PDAM)"],
          [:property, "Dumai", "purple"],
          [:property, "Ambon", "purple"],
          [:railroad, "Stasiun Gambir"],
          [:property, "Banda Aceh", "orange"],
          [:community, "Kotak Amal"],
          [:property, "Mataram", "orange"],
          [:property, "Samarinda", "orange"],
          [:free_parking, "Parkir Gratis"],
          [:property, "Padang", "red"],
          [:chance, "Kesempatan"],
          [:property, "Malang", "red"],
          [:property, "Pontianak", "red"],
          [:railroad, "Bandar Udara Internasional Sentani"],
          [:property, "Jayapura", "yellow"],
          [:property, "Manado", "yellow"],
          [:utility, "Perusahaan Listrik Negara (PLN)"],
          [:property, "Banjarmasin", "yellow"],
          [:neutral, "Zona Pejalan Kaki"],
          [:property, "Balikpapan", "green"],
          [:property, "Denpasar", "green"],
          [:community, "Kotak Amal"],
          [:property, "Yogyakarta", "green"],
          [:railroad, "Bandar Udara Internasional Sultan Hasanuddin"],
          [:chance, "Kesempatan"],
          [:property, "Bekasi", "blue"],
          [:tax_luxury, "Pajak Kemewahan"],
          [:property, "Tangerang", "blue"],
          [:go_to_jail, "Masuk Penjara!"],
          [:property, "Depok", "white"],
          [:utility, "PT Telkom Indonesia"],
          [:property, "Bogor", "white"],
          [:property, "Pekanbaru", "white"],
          [:chance, "Kesempatan"],
          [:property, "Batam", "brown"],
          [:property, "Bandar Lampung", "brown"],
          [:railroad, "Bandar Udara Internasional Kualanamu"],
          [:property, "Palembang", "brown"],
          [:jail, "Penjara, Kunjungan Sederhana"],
          [:property, "Makassar", "gray"],
          [:property, "Semarang", "gray"],
          [:community, "Kotak Amal"],
          [:property, "Bandung", "gray"],
          [:utility, "Perusahaan Tambang dan Minyak Indonesia (PERTAMINA)"],
          [:property, "Medan", "magenta"],
          [:railroad, "Bandar Udara Internasional Soekarno-Hatta"],
          [:property, "Surabaya", "magenta"],
          [:property, "Jakarta", "magenta"],
        ]
      },
      "southeast_asia" => {
        money_factor: 2, currency_symbol: "¤", starting_cash: 7000,
        salary: 500, salary_observed: false, bank_houses: 48, bank_hotels: 18,
        layout: [
          [:start, "Start"],
          [:property, "Nay Pyi Taw", "pink"],
          [:community, "Community chest"],
          [:property, "Mandalay", "pink"],
          [:tax, "Income tax"],
          [:railroad, "Tan Son Nhat International Airport"],
          [:property, "Yangon", "azure"],
          [:chance, "Chance"],
          [:property, "Maliana", "azure"],
          [:property, "Baucau", "azure"],
          [:jail, "Jail, simple visit"],
          [:property, "Dili", "purple"],
          [:utility, "Clean water company"],
          [:property, "Battambang", "purple"],
          [:property, "Siem Reap", "purple"],
          [:railroad, "Ninoy Aquino International Airport"],
          [:property, "Phnom Penh", "orange"],
          [:community, "Community chest"],
          [:property, "Pakse", "orange"],
          [:property, "Savannakhet", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Vientiane", "red"],
          [:chance, "Chance"],
          [:property, "Da Nang", "red"],
          [:property, "Hanoi", "red"],
          [:railroad, "Kuala Lumpur International Airport"],
          [:property, "Ho Chi Minh City", "yellow"],
          [:property, "Davao City", "yellow"],
          [:utility, "Electric company"],
          [:property, "Quezon City", "yellow"],
          [:neutral, "Zone without cars"],
          [:property, "Manila", "green"],
          [:property, "Makassar", "green"],
          [:community, "Community chest"],
          [:property, "Semarang", "green"],
          [:railroad, "Suvarnabhumi International Airport"],
          [:chance, "Chance"],
          [:property, "Bandung", "blue"],
          [:tax_luxury, "Luxury tax"],
          [:property, "Medan", "blue"],
          [:go_to_jail, "Go to jail!"],
          [:property, "Surabaya", "white"],
          [:utility, "Telecom company"],
          [:property, "Jakarta", "white"],
          [:property, "Pattaya", "white"],
          [:chance, "Chance"],
          [:property, "Chiang Mai", "brown"],
          [:property, "Bangkok", "brown"],
          [:railroad, "Soekarno-Hatta International Airport"],
          [:property, "Johor Bahru", "brown"],
          [:neutral, "Public toilet"],
          [:property, "George Town", "gray"],
          [:property, "Kuala Lumpur", "gray"],
          [:community, "Community chest"],
          [:property, "Seria", "gray"],
          [:utility, "Oil company"],
          [:property, "Kuala Belait", "magenta"],
          [:railroad, "Changi International Airport"],
          [:property, "Bandar Seri Begawan", "magenta"],
          [:property, "Singapore", "magenta"],
        ]
      },
      "india" => {
        money_factor: 1, currency_symbol: "₹", starting_cash: 1500,
        salary: 200, salary_observed: false, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Start"],
          [:property, "Shimla", "pink"],
          [:community, "Community Chest"],
          [:property, "Mizoram", "pink"],
          [:tax, "Income Tax"],
          [:railroad, "Agra Station"],
          [:property, "Bhubaneswar", "azure"],
          [:chance, "Chance"],
          [:property, "Lakshadweep", "azure"],
          [:property, "Daman", "azure"],
          [:jail, "Jail"],
          [:property, "Ujjain", "purple"],
          [:utility, "Hydro Power Plant"],
          [:property, "Gangtok", "purple"],
          [:property, "Patna", "purple"],
          [:railroad, "Ernakulam Junction"],
          [:property, "Indore", "orange"],
          [:community, "Community Chest"],
          [:property, "Nagpur", "orange"],
          [:property, "Lucknow", "orange"],
          [:free_parking, "Free Parking"],
          [:property, "Jaipur", "red"],
          [:chance, "Chance"],
          [:property, "Noida", "red"],
          [:property, "Kochi", "red"],
          [:railroad, "Surat Railway Station"],
          [:property, "Pune", "yellow"],
          [:property, "Goa", "yellow"],
          [:utility, "Thermal Power Plant"],
          [:property, "Ahmedabad", "yellow"],
          [:go_to_jail, "Go to Jail"],
          [:property, "Hyderabad", "green"],
          [:property, "Kolkata", "green"],
          [:community, "Community Chest"],
          [:property, "Chennai", "green"],
          [:railroad, "Kempegowda International Airport."],
          [:chance, "Chance"],
          [:property, "Delhi", "blue"],
          [:tax_luxury, "Luxury Tax"],
          [:property, "Mumbai", "blue"],
        ]
      },
      "twelve_nations" => {
        money_factor: 2, currency_symbol: "¤", starting_cash: 7000,
        salary: 500, salary_observed: true, bank_houses: 48, bank_hotels: 18,
        layout: [
          [:start, "Start"],
          [:property, "Linz", "pink"],
          [:community, "Community chest"],
          [:property, "Vienna", "pink"],
          [:tax, "Income tax"],
          [:railroad, "Schiphol airport"],
          [:property, "Rotterdam", "azure"],
          [:chance, "Chance"],
          [:property, "Amsterdam", "azure"],
          [:property, "La Haye", "azure"],
          [:jail, "Jail, simple visit"],
          [:property, "Lisbonna", "purple"],
          [:utility, "Electric company"],
          [:property, "Porto", "purple"],
          [:property, "Bragga", "purple"],
          [:railroad, "London-Heathrow airport"],
          [:property, "Barcelona", "orange"],
          [:community, "Community chest"],
          [:property, "Valencia", "orange"],
          [:property, "Madrid", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Napoli", "red"],
          [:chance, "Chance"],
          [:property, "Roma", "red"],
          [:property, "Bologna", "red"],
          [:railroad, "Roissy-Charles-de-Gaulle airport"],
          [:property, "Bern", "yellow"],
          [:property, "Zürich", "yellow"],
          [:utility, "Water works"],
          [:property, "Geneva", "yellow"],
          [:neutral, "Zone without cars"],
          [:property, "Hamburg", "green"],
          [:property, "Berlin", "green"],
          [:community, "Community chest"],
          [:property, "Münich", "green"],
          [:railroad, "Frankfurt airport"],
          [:chance, "Chance"],
          [:property, "Vaduz", "blue"],
          [:tax_luxury, "Luxury tax"],
          [:property, "Luxembourg", "blue"],
          [:go_to_jail, "Go to jail !"],
          [:property, "Namure", "white"],
          [:utility, "Oil company"],
          [:property, "Bruxelles", "white"],
          [:property, "Liège", "white"],
          [:chance, "Chance"],
          [:property, "Marseille", "brown"],
          [:property, "Lyon", "brown"],
          [:railroad, "Kenneddy airport"],
          [:property, "Paris", "brown"],
          [:neutral, "Public toilet"],
          [:property, "London", "gray"],
          [:property, "Dublin", "gray"],
          [:community, "Community chest"],
          [:property, "Edinbourg", "gray"],
          [:utility, "Telecom company"],
          [:property, "Chicago", "magenta"],
          [:railroad, "Zürich airport"],
          [:property, "Los Angeles", "magenta"],
          [:property, "New york", "magenta"],
        ]
      },
      "europe" => {
        money_factor: 10000, currency_symbol: "€", starting_cash: 15000000,
        salary: 2000000, salary_observed: true, bank_houses: 32, bank_hotels: 12,
        layout: [
          [:start, "Start"],
          [:property, "Vilnius", "pink"],
          [:community, "Community chest"],
          [:property, "Riga", "pink"],
          [:tax, "Income tax"],
          [:railroad, "Schiphol airport"],
          [:property, "Sofia", "azure"],
          [:chance, "Chance"],
          [:property, "Bucarest", "azure"],
          [:property, "Varsovie", "azure"],
          [:jail, "Jail, simple visit"],
          [:property, "Budapest", "purple"],
          [:utility, "European parlament"],
          [:property, "Bern", "purple"],
          [:property, "Helsinki", "purple"],
          [:railroad, "Londons-Heathrow airport"],
          [:property, "Stockholm", "orange"],
          [:community, "Community chest"],
          [:property, "Vienna", "orange"],
          [:property, "Lisbonna", "orange"],
          [:free_parking, "Free parking"],
          [:property, "Madrid", "red"],
          [:chance, "Chance"],
          [:property, "Athena", "red"],
          [:property, "Dublin", "red"],
          [:railroad, "Roissy-Charles-de-Gaulle airport"],
          [:property, "Copenhague", "yellow"],
          [:property, "London", "yellow"],
          [:utility, "European justice"],
          [:property, "Luxembourg", "yellow"],
          [:go_to_jail, "Go to jail !"],
          [:property, "Bruxelles", "green"],
          [:property, "Amsterdam", "green"],
          [:community, "Community chest"],
          [:property, "Roma", "green"],
          [:railroad, "Frankfurt airport"],
          [:chance, "Chance"],
          [:property, "Berlin", "blue"],
          [:tax_luxury, "Luxury tax"],
          [:property, "Paris", "blue"],
        ]
      },
    }.each_value do |profile|
      profile[:layout].each { |square| square.each { |value| value.freeze }; square.freeze }
      profile[:layout].freeze
      profile.freeze
    end.freeze
  end
end
