# encoding: UTF-8
# Generated by tools/quiz-pack-writer.rb; do not edit the checksum by hand.
# Source: https://github.com/budyn1211/elten-game-room/blob/efa6e640a57901e7b01e5ac2158e84f1c3375435/content/quiz_witcher_pl.rb
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.witcher.pl",
  set_id: "quiz.witcher",
  kind: :quiz,
  language_id: "pl-PL",
  version: 1,
  title: "Wiedźmin",
  game_ids: ["quiz"],
  license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)",
  author: "ELTEN Game Room",
  entry_count: 6571,
  checksum: "f0c574035b805bbb6c285d99a842c347817d2432b0d01d498254c3d9906420b9",
  loader: lambda {
    require_relative "quiz_witcher_pl_data"
    GameRoomContent::Pack1f9366a686ccc2dddda06ad6.load
  }
))
