# encoding: UTF-8
# Generated by tools/quiz-pack-writer.rb; do not edit the checksum by hand.
# Source: https://github.com/budyn1211/elten-game-room/blob/efa6e640a57901e7b01e5ac2158e84f1c3375435/content/quiz_pl_wikidata.rb
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.wikidata.pl",
  set_id: "quiz.wikidata",
  kind: :quiz,
  language_id: "pl-PL",
  version: 1,
  title: "Wiedza ogólna: chemia, geografia, sport, wiara, historia",
  game_ids: ["quiz"],
  license: "CC0-1.0",
  author: "ELTEN Game Room",
  entry_count: 15498,
  checksum: "5850da276253ee3e70688ff05a1c670f30fe048279fb0143ad58dba196326206",
  loader: lambda {
    require_relative "quiz_pl_wikidata_data"
    GameRoomContent::Packa0830f585cc4689a1e2a6335.load
  }
))
