# encoding: UTF-8
# Generated by tools/quiz-pack-writer.rb; do not edit the checksum by hand.
# Source: https://github.com/budyn1211/elten-game-room/blob/efa6e640a57901e7b01e5ac2158e84f1c3375435/content/quiz_general_en.rb
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.general.en",
  set_id: "quiz.general",
  kind: :quiz,
  language_id: "en",
  version: 1,
  title: _("General knowledge"),
  game_ids: ["quiz"],
  license: "CC-BY-SA-4.0",
  author: "OpenTriviaQA contributors",
  entry_count: 28575,
  checksum: "35aa0f738cfed6a10b2cdf8d09615e2232dfffa16e69b37cd0c10e77daea09f1",
  loader: lambda {
    require_relative "quiz_general_en_data"
    GameRoomContent::Pack0e7a79bfbaaded2145287ed3.load
  }
))
