# encoding: UTF-8
# Generated by tools/quiz-pack-writer.rb; do not edit the checksum by hand.
# Source: Base pack: https://github.com/budyn1211/elten-game-room/blob/efa6e640a57901e7b01e5ac2158e84f1c3375435/content/quiz_pl_wikidata.rb; sport corrections: content/QUIZ_PL_SPORT_SOURCES.txt; full Polish general-set audit 2026-09-13: content/QUIZ_PL_GENERAL_AUDIT.md and content/QUIZ_PL_GENERAL_REMOVALS.json
require_relative "../lib/game_content"
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "quiz.wikidata.pl",
  set_id: "quiz.wikidata",
  kind: :quiz,
  language_id: "pl-PL",
  version: 1,
  title: "Wiedza ogólna: chemia, geografia, sport, wiara, historia",
  game_ids: ["quiz"],
  author: "ELTEN Game Room",
  license: "CC0-1.0",
  entry_count: 10939,
  checksum: "81ccaf9db72ed54527521be81298ab0930099d1b9f8b88c5132012020fd6a5a5",
  loader: lambda {
    require_relative "quiz_pl_wikidata_data"
    GameRoomContent::Packa0830f585cc4689a1e2a6335.load
  }
))
