# encoding: UTF-8
# Generated by tools/build-taboo-cards.rb.
require_relative '../lib/game_content'
module GameRoomContent::TabooPL; end
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "taboo.general.pl-pl.v1", set_id: 'taboo.general', kind: 'taboo_cards',
  language_id: "pl-PL", version: 1, title: 'General', game_ids: ['taboo'],
  author: 'Game Room editorial', license: 'GPL-3.0-or-later', entry_count: 500,
  checksum: "84b89ca92c1b652ed2cb2ae7e8d1a6166f7aab1445f596897be6181efcb7d13a",
  loader: -> { require_relative "taboo_cards_pl_data"; GameRoomContent::TabooPL.load }
))
module GameRoomContent::TabooEN; end
GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
  id: "taboo.general.en.v1", set_id: 'taboo.general', kind: 'taboo_cards',
  language_id: "en", version: 1, title: 'General', game_ids: ['taboo'],
  author: 'Game Room editorial', license: 'GPL-3.0-or-later', entry_count: 500,
  checksum: "8eb7c706253fce85cd30f6960fcaffe183c81316f3cd99eb413299e7123accaa",
  loader: -> { require_relative "taboo_cards_en_data"; GameRoomContent::TabooEN.load }
))
