# encoding: UTF-8
require "digest"
require "json"
require "time"
require_relative 'support/quiz_write_guard'
require_relative "quiz-pack-writer"
require_relative "../content/quiz_general_en_data"
require_relative "../content/quiz_pl_wikidata_data"
require_relative "../content/quiz_witcher_pl_data"
require_relative "../content/quiz_witcher_pl_medium_data"

root = File.expand_path("..", __dir__)
write_options = QuizWriteGuard.options!(ARGV)
base_audit_root = File.expand_path(ARGV.fetch(0), Dir.pwd)
recovery_root = File.expand_path(ARGV.fetch(1), Dir.pwd)
DATA_VERSION = 4
inputs = %w[ENGLISH_FINAL_DECISIONS.json POLISH_FINAL_DECISIONS_MERGED.json WITCHER_FINAL_DECISIONS.json].map { |name| File.join(base_audit_root, name) }
inputs << File.join(recovery_root, 'ALL_RECHECK_DECISIONS.json')
targets = QuizWriteGuard.content_paths(root)
exit unless QuizWriteGuard.check!(tool: File.basename(__FILE__), inputs: inputs + targets,
  outputs: targets + [File.join(recovery_root, 'APPLIED.json')],
  versions: QuizWriteGuard.versions(root, DATA_VERSION), options: write_options)

def read_json(path)
  JSON.parse(File.read(path, encoding: "UTF-8"))
end

def decision_payload(root, filename)
  read_json(File.join(root, filename))
end

def merged_questions(current_questions, original_decisions, recovery_rows, pack_id)
  current_by_id = current_questions.to_h { |question| [question.fetch("id"), question] }
  raise "duplicate current IDs in #{pack_id}" unless current_by_id.length == current_questions.length

  recovery = recovery_rows.select { |row| row.fetch("pack_id") == pack_id }
  removed_ids = original_decisions.select { |row| row.fetch("decision") == "remove" }.map { |row| row.fetch("id") }
  raise "recovery does not cover every removed ID in #{pack_id}" unless recovery.map { |row| row.fetch("id") }.sort == removed_ids.sort
  restored = recovery.select { |row| row.fetch("decision") == "restore" }
  restored_by_id = restored.to_h { |row| [row.fetch("id"), row.fetch("reviewed")] }

  questions = original_decisions.filter_map do |row|
    id = row.fetch("id")
    if current_by_id.key?(id)
      current_by_id.fetch(id)
    elsif restored_by_id.key?(id)
      restored_by_id.fetch(id)
    end
  end
  known_ids = original_decisions.map { |row| row.fetch("id") }
  questions.concat(current_questions.reject { |question| known_ids.include?(question.fetch("id")) })

  ids = questions.map { |question| question.fetch("id") }
  raise "duplicate merged IDs in #{pack_id}" unless ids.uniq.length == ids.length
  restored.each do |row|
    question = restored_by_id.fetch(row.fetch("id"))
    raise "recovery changed ID #{row.fetch('id')}" unless question.fetch("id") == row.fetch("id")
  end
  [questions, restored]
end

def validate_questions!(questions, pack_id)
  seen = {}
  questions.each do |question|
    id = question.fetch("id")
    options = [question.fetch("correct"), *question.fetch("wrong")]
    normalized = options.map { |value| value.to_s.unicode_normalize(:nfkc).downcase.strip }
    raise "duplicate answer in #{pack_id}/#{id}" unless normalized.uniq.length == normalized.length
    key = [question.fetch("prompt").unicode_normalize(:nfkc).downcase.strip, normalized.first]
    raise "duplicate question in #{pack_id}: #{id} and #{seen[key]}" if seen.key?(key)
    seen[key] = id
  end
end

def write_witcher_medium(path, data)
  json = JSON.pretty_generate(data)
  delimiter = "WITCHER_MEDIUM_DATA_#{Digest::SHA256.hexdigest(JSON.generate(data))}"
  body = <<~RUBY
    # encoding: UTF-8
    # Generated by tools/apply-quiz-recovery-audit.rb; do not edit by hand.
    require "json"
    module GameRoomContent
      module WitcherPolishMediumData
        def self.load
          JSON.parse(<<'#{delimiter}')
    #{json}
    #{delimiter}
        end
      end
    end
  RUBY
  File.write(path, body, encoding: "UTF-8")
end

def pack_checksum(metadata, data)
  GameRoomContent::Pack.new(**metadata, data: data).checksum
end

def write_witcher_registration(path, definitions)
  rows = definitions.map do |definition|
    <<~RUBY.chomp
      {
        id: #{definition.fetch(:id).inspect},
        set_id: #{definition.fetch(:set_id).inspect},
        title: #{definition.fetch(:title).inspect},
        scope: #{definition.fetch(:scope).inspect},
        entry_count: #{definition.fetch(:entry_count)},
        checksum: #{definition.fetch(:checksum).inspect}
      }
    RUBY
  end
  body = <<~RUBY
    # encoding: UTF-8
    # The three sets share one source database and one audited medium map. Their
    # contents are materialized only when the selected set is opened.
    require_relative "../lib/game_content"

    witcher_sets = [
    #{rows.map { |row| row.lines.map { |line| "  #{line}" }.join }.join(",\n")}
    ].freeze

    witcher_sets.each do |definition|
      scope = definition.fetch(:scope)
      GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
        id: definition.fetch(:id),
        set_id: definition.fetch(:set_id),
        kind: :quiz,
        language_id: "pl-PL",
        version: #{DATA_VERSION},
        title: definition.fetch(:title),
        game_ids: ["quiz"],
        license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)",
        author: "ELTEN Game Room",
        entry_count: definition.fetch(:entry_count),
        checksum: definition.fetch(:checksum),
        loader: lambda {
          require_relative "quiz_witcher_pl_sets"
          GameRoomContent::WitcherPolishSets.load(scope)
        }
      ))
    end
  RUBY
  File.write(path, body, encoding: "UTF-8")
end

english_payload = decision_payload(base_audit_root, "ENGLISH_FINAL_DECISIONS.json")
polish_payload = decision_payload(base_audit_root, "POLISH_FINAL_DECISIONS_MERGED.json")
witcher_payload = decision_payload(base_audit_root, "WITCHER_FINAL_DECISIONS.json")
recovery_payload = read_json(File.join(recovery_root, "ALL_RECHECK_DECISIONS.json"))
recovery_rows = recovery_payload.fetch("decisions")

english_current = GameRoomContent::Pack0e7a79bfbaaded2145287ed3.load
polish_current = GameRoomContent::Packa0830f585cc4689a1e2a6335.load
witcher_current = GameRoomContent::Pack1f9366a686ccc2dddda06ad6.load
current_medium = GameRoomContent::WitcherPolishMediumData.load.fetch("media")

english_questions, english_restored = merged_questions(
  english_current.fetch("questions"), english_payload.fetch("decisions"), recovery_rows, "quiz.general.en"
)
polish_questions, polish_restored = merged_questions(
  polish_current.fetch("questions"), polish_payload.fetch("decisions"), recovery_rows, "quiz.wikidata.pl"
)
witcher_questions, witcher_restored = merged_questions(
  witcher_current.fetch("questions"), witcher_payload.fetch("decisions"), recovery_rows, "quiz.witcher.pl"
)
[ [english_questions, "quiz.general.en"], [polish_questions, "quiz.wikidata.pl"], [witcher_questions, "quiz.witcher.pl"] ].each do |questions, pack_id|
  validate_questions!(questions, pack_id)
end

english_pack = QuizPackWriter.write(
  File.join(root, "content", "quiz_general_en.rb"),
  {
    id: "quiz.general.en", set_id: "quiz.general", kind: :quiz,
    language_id: "en", version: DATA_VERSION, title: "General knowledge",
    game_ids: ["quiz"], license: "CC-BY-SA-4.0", author: "OpenTriviaQA contributors"
  },
  english_questions, source: english_current.fetch("source"), translated: true
)

polish_pack = QuizPackWriter.write(
  File.join(root, "content", "quiz_pl_wikidata.rb"),
  {
    id: "quiz.wikidata.pl", set_id: "quiz.wikidata", kind: :quiz,
    language_id: "pl-PL", version: DATA_VERSION,
    title: "Wiedza ogólna: chemia, geografia, sport, wiara, historia",
    game_ids: ["quiz"], license: "CC0-1.0", author: "ELTEN Game Room"
  },
  polish_questions, source: polish_current.fetch("source")
)
polish_registration = File.join(root, "content", "quiz_pl_wikidata.rb")
text = File.read(polish_registration, encoding: "UTF-8")
text.sub!(
  "require_relative \"../lib/game_content\"",
  "# Sport corrections: https://github.com/papierek1997/elten-game-room/commit/2e043a8e0cf5b68df0799a5ffc4a1bb791b24a25\nrequire_relative \"../lib/game_content\""
)
File.write(polish_registration, text, encoding: "UTF-8")

QuizPackWriter.write(
  File.join(root, "content", "quiz_witcher_pl.rb"),
  {
    id: "quiz.witcher.pl", set_id: "quiz.witcher", kind: :quiz,
    language_id: "pl-PL", version: DATA_VERSION, title: "Wiedźmin",
    game_ids: ["quiz"], license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)",
    author: "ELTEN Game Room"
  },
  witcher_questions, source: witcher_current.fetch("source")
)

restored_media = witcher_restored.to_h { |row| [row.fetch("id"), row.fetch("medium")] }
media = witcher_questions.to_h do |question|
  id = question.fetch("id")
  [id, current_medium[id] || restored_media.fetch(id)]
end
medium_data = {
  "version" => DATA_VERSION,
  "source_question_count" => witcher_questions.length,
  "media" => media,
  "prompts" => {}
}
write_witcher_medium(File.join(root, "content", "quiz_witcher_pl_medium_data.rb"), medium_data)

definitions = [
  { id: "quiz.witcher.pl", set_id: "quiz.witcher", title: "Wiedźmin", scope: :all },
  { id: "quiz.witcher.g.pl", set_id: "quiz.witcher.g", title: "Wiedźmin — gry", scope: :games },
  { id: "quiz.witcher.b.pl", set_id: "quiz.witcher.b", title: "Wiedźmin — książki i ekranizacje", scope: :books_screen }
].map do |definition|
  selected = witcher_questions.select do |question|
    code = media.fetch(question.fetch("id"))
    definition.fetch(:scope) == :all || (definition.fetch(:scope) == :games ? code == "g" : code != "g")
  end
  data = { "questions" => selected, "source" => witcher_current.fetch("source"), "data_version" => DATA_VERSION }
  metadata = {
    id: definition.fetch(:id), set_id: definition.fetch(:set_id), kind: :quiz,
    language_id: "pl-PL", version: DATA_VERSION, title: definition.fetch(:title),
    game_ids: ["quiz"], license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)", author: "ELTEN Game Room"
  }
  definition.merge(entry_count: selected.length, checksum: pack_checksum(metadata, data))
end
write_witcher_registration(File.join(root, "content", "quiz_witcher_pl.rb"), definitions)

import_report_path = File.join(root, "content", "QUIZ_IMPORT_REPORT.json")
import_report = read_json(import_report_path)
packs = {
  "quiz.general.en" => [english_payload, english_questions, english_restored, english_pack.checksum],
  "quiz.wikidata.pl" => [polish_payload, polish_questions, polish_restored, polish_pack.checksum],
  "quiz.witcher.pl" => [witcher_payload, witcher_questions, witcher_restored,
    definitions.find { |row| row.fetch(:id) == "quiz.witcher.pl" }.fetch(:checksum)]
}
packs.each do |pack_id, (base_payload, questions, restored, checksum)|
  entry = import_report.fetch("packs").fetch(pack_id)
  rechecks = recovery_rows.select { |row| row.fetch("pack_id") == pack_id }
  entry["pre_factual_audit"] = base_payload.fetch("question_count")
  entry["kept"] = questions.length
  entry["rejected"] = rechecks.select { |row| row.fetch("decision") == "remain_removed" }.map do |row|
    { "id" => row.fetch("id"), "reason" => row.fetch("reason"), "prompt" => row.fetch("original").fetch("prompt") }
  end
  entry["restored_after_second_audit"] = restored.map { |row| row.fetch("id") }
  entry["checksum"] = checksum
  entry["data_version"] = DATA_VERSION
  entry["factual_audit"] = {
    "version" => 2,
    "base_decision_report" => "diagnostics/quiz-factual-audit-220/ALL_DECISIONS.json",
    "recovery_decision_report" => "diagnostics/quiz-recovery-audit-after-221/ALL_RECHECK_DECISIONS.json"
  }
end
witcher_entry = import_report.fetch("packs").fetch("quiz.witcher.pl")
witcher_entry["derived_sets"] = definitions.reject { |row| row.fetch(:id) == "quiz.witcher.pl" }.to_h do |row|
  [row.fetch(:id), { "questions" => row.fetch(:entry_count), "checksum" => row.fetch(:checksum) }]
end
File.write(import_report_path, JSON.pretty_generate(import_report) + "\n", encoding: "UTF-8")

result = {
  "applied_at" => Time.now.utc.iso8601,
  "data_version" => DATA_VERSION,
  "source_removed_questions_rechecked" => recovery_rows.length,
  "english" => { "questions" => english_questions.length, "restored" => english_restored.length, "checksum" => english_pack.checksum },
  "polish" => { "questions" => polish_questions.length, "restored" => polish_restored.length, "checksum" => polish_pack.checksum },
  "witcher" => {
    "questions" => witcher_questions.length,
    "restored" => witcher_restored.length,
    "media" => media.values.tally,
    "sets" => definitions.to_h { |row| [row.fetch(:id), row.slice(:entry_count, :checksum)] }
  }
}
File.write(File.join(recovery_root, "APPLIED.json"), JSON.pretty_generate(result) + "\n", encoding: "UTF-8")
puts JSON.pretty_generate(result)
