# encoding: UTF-8
require "digest"
require "json"
require "time"
require_relative 'support/quiz_write_guard'
require_relative "quiz-pack-writer"
require_relative "../content/quiz_general_en_data"
require_relative "../content/quiz_pl_wikidata_data"
require_relative "../content/quiz_witcher_pl_data"
require_relative "../content/quiz_witcher_pl_medium_data"

root = File.expand_path("..", __dir__)
write_options = QuizWriteGuard.options!(ARGV)
audit_root = File.expand_path(ARGV.fetch(0), Dir.pwd)
inputs = %w[ENGLISH_FINAL_DECISIONS.json POLISH_FINAL_DECISIONS_MERGED.json WITCHER_FINAL_DECISIONS.json].map { |name| File.join(audit_root, name) }
targets = QuizWriteGuard.content_paths(root)
exit unless QuizWriteGuard.check!(tool: File.basename(__FILE__), inputs: inputs + targets,
  outputs: targets + [File.join(audit_root, 'APPLIED.json')], versions: QuizWriteGuard.versions(root, 3), options: write_options)

def read_decisions(audit_root, filename)
  path = File.join(audit_root, filename)
  payload = JSON.parse(File.read(path, encoding: "UTF-8"))
  [payload, payload.fetch("decisions")]
end

def reviewed_questions(source_questions, decisions)
  source_ids = source_questions.map { |question| question.fetch("id") }
  decision_ids = decisions.map { |row| row.fetch("id") }
  raise "duplicate source IDs" if source_ids.uniq.length != source_ids.length
  raise "duplicate audit decisions" if decision_ids.uniq.length != decision_ids.length
  original_ids = decisions.map { |row| row.fetch("original").fetch("id") }
  raise "audit changed an original question ID" if original_ids != decision_ids

  retained_ids = decisions.reject { |row| row.fetch("decision") == "remove" }.map { |row| row.fetch("id") }
  # Allow both the untouched source and an already-applied audited source. This
  # makes the mechanical writer idempotent without weakening decision coverage.
  untouched_source = source_ids.sort == decision_ids.sort
  previously_applied_source = (retained_ids - source_ids).empty? && (source_ids - decision_ids).empty?
  unless untouched_source || previously_applied_source
    raise "audit decisions do not cover the source pack"
  end
  by_id = decisions.to_h { |row| [row.fetch('id'), row] }
  source_questions.each do |question|
    row = by_id.fetch(question.fetch('id'))
    unless question == row.fetch('original') || question == row['reviewed']
      raise "question changed since this historical review: #{question.fetch('id')}"
    end
  end

  decisions.filter_map do |row|
    next if row.fetch("decision") == "remove"
    reviewed = row.fetch("reviewed")
    raise "retained question has no reviewed form: #{row.fetch('id')}" if reviewed == nil
    raise "audit changed a question ID" if reviewed.fetch("id") != row.fetch("id")
    reviewed
  end
end

def write_witcher_medium(path, data)
  json = JSON.pretty_generate(data)
  delimiter = "WITCHER_MEDIUM_DATA_#{Digest::SHA256.hexdigest(JSON.generate(data))}"
  body = <<~RUBY
    # encoding: UTF-8
    # Generated by tools/apply-quiz-factual-audit.rb; do not edit by hand.
    require "json"
    module GameRoomContent
      module WitcherPolishMediumData
        def self.load
          JSON.parse(<<'#{delimiter}')
    #{json}
    #{delimiter}
        end
      end
    end
  RUBY
  File.write(path, body, encoding: "UTF-8")
end

def pack_checksum(metadata, data)
  GameRoomContent::Pack.new(**metadata, data: data).checksum
end

def write_witcher_registration(path, definitions)
  rows = definitions.map do |definition|
    <<~RUBY.chomp
      {
        id: #{definition.fetch(:id).inspect},
        set_id: #{definition.fetch(:set_id).inspect},
        title: #{definition.fetch(:title).inspect},
        scope: #{definition.fetch(:scope).inspect},
        entry_count: #{definition.fetch(:entry_count)},
        checksum: #{definition.fetch(:checksum).inspect}
      }
    RUBY
  end
  body = <<~RUBY
    # encoding: UTF-8
    # The three sets share one source database and one audited medium map. Their
    # contents are materialized only when the selected set is opened.
    require_relative "../lib/game_content"

    witcher_sets = [
    #{rows.map { |row| row.lines.map { |line| "  #{line}" }.join }.join(",\n")}
    ].freeze

    witcher_sets.each do |definition|
      scope = definition.fetch(:scope)
      GameRoomContent.registry.register_pack(GameRoomContent::Pack.new(
        id: definition.fetch(:id),
        set_id: definition.fetch(:set_id),
        kind: :quiz,
        language_id: "pl-PL",
        version: 3,
        title: definition.fetch(:title),
        game_ids: ["quiz"],
        license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)",
        author: "ELTEN Game Room",
        entry_count: definition.fetch(:entry_count),
        checksum: definition.fetch(:checksum),
        loader: lambda {
          require_relative "quiz_witcher_pl_sets"
          GameRoomContent::WitcherPolishSets.load(scope)
        }
      ))
    end
  RUBY
  File.write(path, body, encoding: "UTF-8")
end

english_payload, english_decisions = read_decisions(audit_root, "ENGLISH_FINAL_DECISIONS.json")
polish_payload, polish_decisions = read_decisions(audit_root, "POLISH_FINAL_DECISIONS_MERGED.json")
witcher_payload, witcher_decisions = read_decisions(audit_root, "WITCHER_FINAL_DECISIONS.json")

english_source = GameRoomContent::Pack0e7a79bfbaaded2145287ed3.load
polish_source = GameRoomContent::Packa0830f585cc4689a1e2a6335.load
witcher_source = GameRoomContent::Pack1f9366a686ccc2dddda06ad6.load

english_questions = reviewed_questions(english_source.fetch("questions"), english_decisions)
polish_questions = reviewed_questions(polish_source.fetch("questions"), polish_decisions)
witcher_questions = reviewed_questions(witcher_source.fetch("questions"), witcher_decisions)

english_pack = QuizPackWriter.write(
  File.join(root, "content", "quiz_general_en.rb"),
  {
    id: "quiz.general.en", set_id: "quiz.general", kind: :quiz,
    language_id: "en", version: 3, title: "General knowledge",
    game_ids: ["quiz"], license: "CC-BY-SA-4.0",
    author: "OpenTriviaQA contributors"
  },
  english_questions,
  source: english_source["source"],
  translated: true
)

polish_pack = QuizPackWriter.write(
  File.join(root, "content", "quiz_pl_wikidata.rb"),
  {
    id: "quiz.wikidata.pl", set_id: "quiz.wikidata", kind: :quiz,
    language_id: "pl-PL", version: 3,
    title: "Wiedza ogólna: chemia, geografia, sport, wiara, historia",
    game_ids: ["quiz"], license: "CC0-1.0", author: "ELTEN Game Room"
  },
  polish_questions,
  source: polish_source["source"]
)
polish_registration = File.join(root, "content", "quiz_pl_wikidata.rb")
polish_text = File.read(polish_registration, encoding: "UTF-8")
polish_text.sub!(
  "require_relative \"../lib/game_content\"",
  "# Sport corrections: https://github.com/papierek1997/elten-game-room/commit/2e043a8e0cf5b68df0799a5ffc4a1bb791b24a25\nrequire_relative \"../lib/game_content\""
)
File.write(polish_registration, polish_text, encoding: "UTF-8")

# QuizPackWriter creates the shared lazy source resource and guarantees the
# stable module name derived from quiz.witcher.pl. The three-set registration
# is restored immediately below.
QuizPackWriter.write(
  File.join(root, "content", "quiz_witcher_pl.rb"),
  {
    id: "quiz.witcher.pl", set_id: "quiz.witcher", kind: :quiz,
    language_id: "pl-PL", version: 3, title: "Wiedźmin",
    game_ids: ["quiz"], license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)",
    author: "ELTEN Game Room"
  },
  witcher_questions,
  source: witcher_source["source"]
)

retained_witcher_ids = witcher_questions.map { |question| question.fetch("id") }
witcher_by_id = witcher_decisions.to_h { |row| [row.fetch("id"), row] }
media = retained_witcher_ids.to_h { |id| [id, witcher_by_id.fetch(id).fetch("medium")] }
medium_data = {
  "version" => 3,
  "source_question_count" => witcher_questions.length,
  "media" => media,
  "prompts" => {}
}
write_witcher_medium(File.join(root, "content", "quiz_witcher_pl_medium_data.rb"), medium_data)

definitions = [
  { id: "quiz.witcher.pl", set_id: "quiz.witcher", title: "Wiedźmin", scope: :all },
  { id: "quiz.witcher.g.pl", set_id: "quiz.witcher.g", title: "Wiedźmin — gry", scope: :games },
  { id: "quiz.witcher.b.pl", set_id: "quiz.witcher.b", title: "Wiedźmin — książki i ekranizacje", scope: :books_screen }
].map do |definition|
  selected = witcher_questions.select do |question|
    code = media.fetch(question.fetch("id"))
    definition.fetch(:scope) == :all ||
      (definition.fetch(:scope) == :games ? code == "g" : code != "g")
  end
  data = {
    "questions" => selected,
    "source" => witcher_source.fetch("source"),
    "data_version" => 3
  }
  metadata = {
    id: definition.fetch(:id), set_id: definition.fetch(:set_id), kind: :quiz,
    language_id: "pl-PL", version: 3, title: definition.fetch(:title),
    game_ids: ["quiz"], license: "CC BY-SA 3.0 (Fandom, Wiedźmin Wiki)",
    author: "ELTEN Game Room"
  }
  definition.merge(entry_count: selected.length, checksum: pack_checksum(metadata, data))
end
write_witcher_registration(File.join(root, "content", "quiz_witcher_pl.rb"), definitions)

result = {
  "applied_at" => Time.now.utc.iso8601,
  "english" => {
    "source" => english_payload.fetch("question_count"),
    "retained" => english_questions.length,
    "checksum" => english_pack.checksum,
    "version" => 3
  },
  "polish" => {
    "source" => polish_payload.fetch("question_count"),
    "retained" => polish_questions.length,
    "checksum" => polish_pack.checksum,
    "version" => 3
  },
  "witcher" => {
    "source" => witcher_payload.fetch("question_count"),
    "retained" => witcher_questions.length,
    "media" => media.values.tally,
    "sets" => definitions.to_h { |row| [row.fetch(:id), row.slice(:entry_count, :checksum)] },
    "version" => 3
  }
}

import_report_path = File.join(root, "content", "QUIZ_IMPORT_REPORT.json")
import_report = JSON.parse(File.read(import_report_path, encoding: "UTF-8"))
[
  ["quiz.general.en", english_decisions, english_questions, english_pack, english_payload],
  ["quiz.wikidata.pl", polish_decisions, polish_questions, polish_pack, polish_payload]
].each do |pack_id, decisions, retained, pack, payload|
  entry = import_report.fetch("packs").fetch(pack_id)
  entry["pre_factual_audit"] = payload.fetch("question_count")
  entry["kept"] = retained.length
  entry["changed"] = decisions.select { |row| row.fetch("decision") == "correct" }.map { |row| row.fetch("id") }
  entry["rejected"] = decisions.select { |row| row.fetch("decision") == "remove" }.map do |row|
    {
      "id" => row.fetch("id"),
      "reason" => row.fetch("reason"),
      "prompt" => row.fetch("original").fetch("prompt")
    }
  end
  entry["checksum"] = pack.checksum
  entry["data_version"] = 3
  entry["factual_audit"] = {
    "version" => 1,
    "decision_report" => "diagnostics/quiz-factual-audit-220/ALL_DECISIONS.json"
  }
end

witcher_entry = import_report.fetch("packs").fetch("quiz.witcher.pl")
witcher_entry["pre_factual_audit"] = witcher_payload.fetch("question_count")
witcher_entry["kept"] = witcher_questions.length
witcher_entry["changed"] = witcher_decisions.select { |row| row.fetch("decision") == "correct" }.map { |row| row.fetch("id") }
witcher_entry["rejected"] = witcher_decisions.select { |row| row.fetch("decision") == "remove" }.map do |row|
  {
    "id" => row.fetch("id"),
    "reason" => row.fetch("reason"),
    "prompt" => row.fetch("original").fetch("prompt")
  }
end
witcher_entry["data_version"] = 3
witcher_entry["checksum"] = definitions.find { |row| row.fetch(:id) == "quiz.witcher.pl" }.fetch(:checksum)
witcher_entry["derived_sets"] = definitions.reject { |row| row.fetch(:id) == "quiz.witcher.pl" }.to_h do |row|
  [row.fetch(:id), { "questions" => row.fetch(:entry_count), "checksum" => row.fetch(:checksum) }]
end
witcher_entry["factual_audit"] = {
  "version" => 1,
  "decision_report" => "diagnostics/quiz-factual-audit-220/ALL_DECISIONS.json"
}
File.write(import_report_path, JSON.pretty_generate(import_report) + "\n", encoding: "UTF-8")

File.write(File.join(audit_root, "APPLIED.json"), JSON.pretty_generate(result) + "\n", encoding: "UTF-8")
puts JSON.pretty_generate(result)
