require "digest"
require "json"
require "optparse"

options = {
  language: "pl-PL",
  license: "CC0-1.0",
  version: 1,
  author: "ELTEN Game Room"
}

OptionParser.new do |parser|
  parser.on("--json PATH") { |value| options[:json] = value }
  parser.on("--out PATH") { |value| options[:out] = value }
  parser.on("--set-id ID") { |value| options[:set_id] = value }
  parser.on("--pack-id ID") { |value| options[:pack_id] = value }
  parser.on("--title TITLE") { |value| options[:title] = value }
  parser.on("--language ID") { |value| options[:language] = value }
  parser.on("--license NAME") { |value| options[:license] = value }
  parser.on("--source TEXT") { |value| options[:source] = value }
  parser.on("--author NAME") { |value| options[:author] = value }
  parser.on("--version NUMBER") { |value| options[:version] = value.to_i }
  parser.on("--translated") { options[:translated] = true }
end.parse!

%i[json out set_id pack_id title].each do |key|
  abort "missing --#{key.to_s.tr('_', '-')}" if options[key].to_s.empty?
end

raw = JSON.parse(File.read(options[:json], encoding: "utf-8"))
questions = raw.is_a?(Array) ? raw : (raw["questions"] || raw["pytania"])
abort "the JSON file contains no questions" if !questions.is_a?(Array) || questions.empty?

LEVELS = %w[easy medium hard].freeze

def ruby_string(text)
  JSON.generate(text.to_s).gsub("#", '\\#')
end

def comment_text(text)
  text.to_s.gsub(/[[:cntrl:]]+/, " ").strip
end

seen_ids = {}
problems = []
prepared = questions.each_with_index.map do |question, index|
  category = question["category"].to_s.strip
  level = question["level"].to_s.strip
  prompt = question["prompt"].to_s.strip
  correct = question["correct"].to_s.strip
  wrong = Array(question["wrong"]).map { |value| value.to_s.strip }.reject(&:empty?)

  problems << "question #{index + 1} has no category" if category.empty?
  problems << "question #{index + 1} has no prompt" if prompt.empty?
  problems << "question #{index + 1} has no correct answer" if correct.empty?
  problems << "question #{index + 1} (#{prompt}) has #{wrong.length} wrong answers instead of 3" if wrong.length != 3
  problems << "question #{index + 1} (#{prompt}) has an unknown level #{level.inspect}" if !LEVELS.include?(level)
  all = ([correct] + wrong).map(&:downcase)
  problems << "question #{index + 1} (#{prompt}) repeats an answer" if all.uniq.length != all.length

  id = Digest::SHA256.hexdigest("#{options[:set_id]}|#{category}|#{prompt}")[0, 12]
  problems << "question #{index + 1} (#{prompt}) duplicates #{seen_ids[id]}" if seen_ids.key?(id)
  seen_ids[id] = prompt

  {
    id: id,
    category: category,
    level: level,
    prompt: prompt,
    correct: correct,
    wrong: wrong
  }
end

if !problems.empty?
  warn "the pack was not written, #{problems.length} problem(s) found:"
  problems.first(30).each { |problem| warn "  #{problem}" }
  exit 1
end

prepared.sort_by! { |question| [question[:category], LEVELS.index(question[:level]), question[:prompt]] }

lines = []
lines << "# #{comment_text(options[:title])} question pack for Quiz Party."
lines << "# Generated by tools/build-quiz-pack.rb from #{comment_text(File.basename(options[:json]))}."
source = comment_text(options[:source])
lines << "# Source: #{source}" if !source.empty?
lines << "# The wrong answers are drawn from correct answers of the same"
lines << "# category, so every choice is the same kind of thing."
lines << ""
lines << %(require_relative "../lib/game_content")
lines << ""
lines << "GameRoomContent.registry.register_pack("
lines << "  GameRoomContent::Pack.new("
lines << "    id: #{ruby_string(options[:pack_id])},"
lines << "    set_id: #{ruby_string(options[:set_id])},"
lines << "    kind: :quiz,"
lines << "    language_id: #{ruby_string(options[:language])},"
lines << "    version: #{options[:version]},"
title = options[:translated] ? "_(#{ruby_string(options[:title])})" : ruby_string(options[:title])
lines << "    title: #{title},"
lines << %(    game_ids: ["quiz"],)
lines << "    author: #{ruby_string(options[:author])},"
lines << "    license: #{ruby_string(options[:license])},"
lines << "    data: {"
lines << "      questions: ["
prepared.each_with_index do |question, index|
  lines << "        {"
  lines << "          id: #{ruby_string(question[:id])},"
  lines << "          category: #{ruby_string(question[:category])},"
  lines << "          level: #{ruby_string(question[:level])},"
  lines << "          prompt: #{ruby_string(question[:prompt])},"
  lines << "          correct: #{ruby_string(question[:correct])},"
  lines << "          wrong: [#{question[:wrong].map { |value| ruby_string(value) }.join(', ')}]"
  lines << (index == prepared.length - 1 ? "        }" : "        },")
end
lines << "      ]"
lines << "    }"
lines << "  )"
lines << ")"
lines << ""

File.write(options[:out], lines.join("\n"), encoding: "utf-8")

counts = prepared.group_by { |question| question[:category] }.transform_values(&:length)
levels = prepared.group_by { |question| question[:level] }.transform_values(&:length)
puts "wrote #{options[:out]}: #{prepared.length} questions"
puts "  categories: #{counts.sort.map { |name, count| "#{name}=#{count}" }.join(', ')}"
puts "  levels: #{LEVELS.map { |name| "#{name}=#{levels[name] || 0}" }.join(', ')}"
